#!/bin/sh

## Reset files
rm a.out
rm a.exe
rm ./export/* -r

## Recreate the file structure
mkdir export/cDataLib
mkdir export/cDataLib/lib
#mkdir export/cDataLib/lib/dll
mkdir export/cDataLib/lib/so

## Move headers in their place
cp headers export/cDataLib/ -r
cp cDataLib.h export/cDataLib/

## Compile for Windows (Cross platform test)
../tcc_win/tcc.exe -Ofast -w ./src/*/*.c test.c -o a.exe

## Compile for *nix
    ## Create a shared library
    #gcc -g -Ofast -shared -fPIC ./src/*/*.c -o export/cDataLib/lib/libdata.so
    #gcc -shared -fPIC -w ./src/*/*.c -o export/cDataLib/lib/libdata.so
    gcc -Ofast -shared -w -fPIC ./src/*/*.c -o export/cDataLib/lib/so/libdata.so

## Form the directory structure
sudo cp export/cDataLib/lib/so/libdata.so /usr/lib/
sudo chmod 755 /usr/lib/libdata.so
cp LICENSE export/cDataLib/
cp README.md export/cDataLib/
cp export/cDataLib ../../uoi/java/DataStructures/PDPs/ -r

## Compile the test file using the shared library
#gcc -w test.c -ldata
gcc -Ofast -w test.c -ldata

## Run the test files
./a.out
#./a.exe
