#!/bin/sh

gcc -O2 -std=c89 -Wno-incompatible-pointer-types -Wno-int-conversion test.c \
    ../src/vector/*.c \
    ../src/hashmap/*.c \
    ../src/string/*.c \
    ../src/linked_list/*.c \
    ../src/stack/*.c

./a.out
