#!/bin/sh

rm a.out

./compile_all

## Compile the test file using the shared library
gcc -Ofast -Wno-incompatible-pointer-types -Wno-int-conversion -Wno-pointer-to-int-cast test.c -lsuite

## Compile using the dll
#cp ../lib/cSuite/lib/dll/libsuite.dll ./
#../../tcc/tcc_win/tcc.exe -Ofast -Wno-incompatible-pointer-types -Wno-int-conversion test.c -o a.exe

## Run the test files
./a.out
