#!/bin/sh

## Reset files
rm ./lib/* -r
rmdir lib

## Recreate the file structure
mkdir lib
mkdir lib/cSuite
mkdir lib/cSuite/lib
mkdir lib/cSuite/lib/dll
mkdir lib/cSuite/lib/so

cat << EOF > lib/cSuite.h
#ifndef __C_SUITE_LIBRARY_H_
#define __C_SUITE_LIBRARY_H_

#include "cSuite/cSuite.h"

#endif
EOF

mkdir lib/cSuite/cAutomations/headers -p
mkdir lib/cSuite/cDataLib/headers -p
mkdir lib/cSuite/cLitterBin/headers -p
mkdir lib/cSuite/cObject/headers -p
mkdir lib/cSuite/cSpec/headers -p

## Move headers in their place
cp cAutomations/headers/* lib/cSuite/cAutomations/headers -r
cp cAutomations/__all.h cAutomations/README.md lib/cSuite/cAutomations
cp cDataLib/headers/* lib/cSuite/cDataLib/headers -r
cp cDataLib/__all.h cDataLib/README.md lib/cSuite/cDataLib
cp cLitterBin/headers/* lib/cSuite/cLitterBin/headers -r
cp cLitterBin/__all.h cLitterBin/README.md lib/cSuite/cLitterBin
cp cSpec/headers/* lib/cSuite/cSpec/headers -r
cp cSpec/__all.h cSpec/README.md lib/cSuite/cSpec
cp cSuite.h lib/cSuite
cp includes.h lib/cSuite

## Compile for Windows (Cross platform test)
#../tcc/tcc_win/tcc.exe -Ofast -shared -Wno-incompatible-pointer-types -Wno-int-conversion -fPIC cAutomations/src/*.c cDataLib/src/*/*.c cLitterBin/src/*.c -o lib/cSuite/lib/dll/libsuite.dll

## Compile for *nix
    ## Create a shared library
    gcc -Ofast -shared -Wno-incompatible-pointer-types -Wno-int-conversion -Wno-pointer-to-int-cast -fPIC cAutomations/src/*.c cLitterBin/src/*.c cDataLib/src/*/*.c -o lib/cSuite/lib/so/libsuite.so

## Form the directory structure
sudo cp lib/cSuite/lib/so/libsuite.so /usr/lib/
sudo chmod 755 /usr/lib/libsuite.so
cp LICENSE lib/cSuite/
cp README.md lib/cSuite/
